# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4b4e35144c5052c21723baab0d7e1d3bddc177e3d77a09603e883b4105050d94b81d0b45d913dd1f0602819ad417759f9148e2d77e055e4bf8c4c71be964f5

test:
  secret_key_base: 90043ce34786d97fd02794d6d4774f7072a445ecb7a276d84d68e754835dfa5b826104cba865d31aebb380b55b907c0b25a4bcb6c36f994e9cc38e6745a232bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
